name: tic_tac_toe
description: "A new tic_tac_toe app"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  audioplayers: ^6.6.0
  confetti: ^0.8.0
  vibration: ^3.1.8
  fluttertoast: ^9.0.0
  firebase_core: ^4.7.0
  firebase_database: ^12.3.0
  share_plus: ^13.0.0
  image_picker: ^1.0.7
  connectivity_plus: ^7.1.1
  marquee: ^2.2.3
  app_links: ^6.0.0
  lottie: ^3.1.0

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  flutter_lints: ^6.0.0

  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/tap.mp3
    - assets/audio/win.mp3
    - assets/audio/lose.mp3
    - assets/audio/draw.mp3
    - assets/audio/tick.mp3
    - assets/lottie/sandy_loading.json
    - assets/lottie/material_wave_loading.json
    - assets/lottie/loading_animation_blue.json
    - assets/lottie/tic_tac_toe_light.json
    - assets/lottie/tic_tac_toe_dark.json