// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk6u-KKmzVKNNZpaVVCbVA_qd13u1jKtA',
    appId: '1:822658804517:web:fe28026f24eafa6ecc08cc',
    messagingSenderId: '822658804517',
    projectId: 'tic-tac-toe-9c3bf',
    authDomain: 'tic-tac-toe-9c3bf.firebaseapp.com',
    databaseURL: 'https://tic-tac-toe-9c3bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-9c3bf.firebasestorage.app',
    measurementId: 'G-2JLYK9Y4PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRRgg_JXtZu5TxyAxGPDx9tgdWtFIJl8',
    appId: '1:822658804517:android:4a36fe0041927c92cc08cc',
    messagingSenderId: '822658804517',
    projectId: 'tic-tac-toe-9c3bf',
    databaseURL: 'https://tic-tac-toe-9c3bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-9c3bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiYZpX9TcghPcLDrgnLqUV_qS0HXMBWDU',
    appId: '1:822658804517:ios:9217aa3ed2800eeecc08cc',
    messagingSenderId: '822658804517',
    projectId: 'tic-tac-toe-9c3bf',
    databaseURL: 'https://tic-tac-toe-9c3bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-9c3bf.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiYZpX9TcghPcLDrgnLqUV_qS0HXMBWDU',
    appId: '1:822658804517:ios:9217aa3ed2800eeecc08cc',
    messagingSenderId: '822658804517',
    projectId: 'tic-tac-toe-9c3bf',
    databaseURL: 'https://tic-tac-toe-9c3bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-9c3bf.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk6u-KKmzVKNNZpaVVCbVA_qd13u1jKtA',
    appId: '1:822658804517:web:5689130be815a27acc08cc',
    messagingSenderId: '822658804517',
    projectId: 'tic-tac-toe-9c3bf',
    authDomain: 'tic-tac-toe-9c3bf.firebaseapp.com',
    databaseURL: 'https://tic-tac-toe-9c3bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-9c3bf.firebasestorage.app',
    measurementId: 'G-7MH5WD14KF',
  );
}
